### ISSUE TITLE
LoadError while trying to require 'rubinius/debugger'

### ISSUE THREAD

**Issue by goyox86** [rubinius/rubinius-debugger#2]
I'm getting a LoadError while I try to require RBX debugger:  

```bash
pry(main)> require 'rubinius/debugger'
LoadError: no such file to load -- rubinius/compiler/iseq
from kernel/common/code_loader.rb:439:in `load_error'
[2] pry(main)>
```

This is my rbx -v:

```bash
rubinius 2.1.1 (2.1.0 be67ed17 2013-10-18 JI) [x86_64-darwin12.5.0]
```
And this is my uname -a:

```bash
Darwin Joseito.local 12.5.0 Darwin Kernel Version 12.5.0: Mon Jul 29 16:33:49 PDT 2013; root:xnu-2050.48.11~1/RELEASE_X86_64 x86_64
```

**Comment by tak1n** [comment]
`rubinius-compiler` is a preinstalled gem see: https://github.com/rubinius/rubinius/blob/master/gems_list.txt

Also documentation about these dependencies has been added, therefore this can be closed.
@goyox86 can you close it, or someone who has access to the repo like @brixen, @jc00ke
